FROM ubuntu:18.04
LABEL author="Sundeep M"
LABEL Org="Sundeep Mulampaka Organization"
RUN apt-get update
RUN apt-get install apache2 -y
RUN apt-get install git -y
VOLUME [ "/var/www/html" ]
CMD [ "apache2ctl","-D", "FOREGROUND"]