FROM openjdk:17
LABEL org="smulampa Org"
LABEL auth="smulampa Organization"
RUN wget https://myspappstorage.s3.us-west-1.amazonaws.com/spring-petclinic-2.4.2.jar
EXPOSE 8080
CMD [ "java", "-jar", "spring-petclinic-2.4.2.jar" ]